# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f26b1328b801fe1698b283adac2f5ad9a7f46d147d6d1b78a0cbee8178a4b0c4924c6d987c91adc6fd0ff217b2562806cd3e065b973d2f88b1d9c8c04e1a837d

test:
  secret_key_base: 037f906a4cce045fa72f582516a53414e43bf4c3db63b69a7a4210e12956f915d84573d48b8e91a991a088c209494a6a6850040cc6041c52a4c343a92c300db4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
